#!/bin/bash
#
# Cluster PostgreSQL Service Script
#
# By Reinaldo Martinez P.
# Caracas, Venezuela.
# TigerLinux AT gmail DOT com
#

mystatus=`/usr/local/bin/postgres-db-control.sh status 2>/dev/null|grep -ci "server is running"`

case $1 in
start)
        echo "Starting Postgres DB Services"
        echo "0" > /var/log/db-svc-started.log
        rm -f /var/log/db-svc-stopped.log
        /usr/local/bin/postgres-db-control.sh start > /dev/null 2>&1
        exit 0
        ;;
stop)
        echo "Stopping Postgres DB Services"
        rm -f /var/log/db-svc-started.log
        echo "0" > /var/log/db-svc-stopped.log
        /usr/local/bin/postgres-db-control.sh stopfast > /dev/null 2>&1
        exit 0
        ;;
status)
        echo "Postgres DB Services Status"
        if [ $mystatus == "0" ]
        then
                rm -f /var/log/db-svc-started.log
                echo "0" > /var/log/db-svc-stopped.log
                exit 3
        else
                echo "0" > /var/log/db-svc-started.log
                rm -f /var/log/db-svc-stopped.log
                exit 0
        fi
        ;;
restart)
        echo "Postgres DB Services Restart"
        /usr/local/bin/postgres-db-control.sh stopfast > /dev/null 2>&1
        /usr/local/bin/postgres-db-control.sh start > /dev/null 2>&1
        rm -f /var/log/db-svc-stopped.log
        echo "0" > /var/log/db-svc-started.log
        exit 0
        ;;
esac
